do $$
begin
  if to_regclass('public.chat_messages') is null then
    create table public.chat_messages (
      id bigint generated by default as identity primary key,
      user_id text not null,
      role text not null check (role in ('user', 'assistant')),
      content text not null,
      metadata jsonb not null default '{}'::jsonb,
      created_at timestamptz not null default now()
    );
  end if;
end $$;

alter table if exists public.sensor_data
  add column if not exists formula_name text,
  add column if not exists formula_soil text,
  add column if not exists formula_vpd text,
  add column if not exists formula_score text,
  add column if not exists soil_raw_dry numeric;

alter table if exists public.chat_messages
  add column if not exists metadata jsonb not null default '{}'::jsonb;

comment on column public.sensor_data.formula_name is 'Nama formula Arduino yang dipakai untuk kalkulasi sensor.';
comment on column public.sensor_data.formula_soil is 'Rumus soil moisture dari Arduino.';
comment on column public.sensor_data.formula_vpd is 'Rumus VPD dari Arduino.';
comment on column public.sensor_data.formula_score is 'Rumus total skor dari Arduino.';
comment on column public.sensor_data.soil_raw_dry is 'Nilai kalibrasi raw tanah kering dari Arduino.';
comment on column public.chat_messages.metadata is 'Snapshot sensor, settings, dan formula saat chat disimpan.';
